/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zw_app_WasmEdge */

#ifndef _Included_com_zw_app_WasmEdge
#define _Included_com_zw_app_WasmEdge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zw_app_WasmEdge
 * Method:    wasm_init
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_zw_app_WasmEdge_wasm_1init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_zw_app_WasmEdge
 * Method:    wasm_exec
 * Signature: (J[BLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zw_app_WasmEdge_wasm_1exec
  (JNIEnv *, jobject, jlong, jbyteArray, jstring, jstring);

/*
 * Class:     com_zw_app_WasmEdge
 * Method:    wasm_release
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zw_app_WasmEdge_wasm_1release
  (JNIEnv *env, jobject, jlong, jstring){

}

#ifdef __cplusplus
}
#endif
#endif
